# Generated by Django 3.1.2 on 2021-03-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=10)),
                ('fitness_level', models.CharField(max_length=10)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('bmi', models.CharField(max_length=10)),
                ('fat_per', models.CharField(max_length=10)),
            ],
        ),
    ]
